import React, { useState, useEffect, useRef, useCallback, useLayoutEffect } from 'react';
import { Session, RealtimeChannel } from '@supabase/supabase-js';
import { supabase } from '../services/supabaseClient';
import { Profile, Message, PresenceState } from '../types';
import Avatar from '../components/Avatar';

interface ChatPageProps {
  session: Session;
  theme: 'light' | 'dark';
  toggleTheme: () => void;
}

const DatabaseSetupGuide: React.FC<{ error: string }> = ({ error }) => {
    const sqlScript = `-- IMPORTANT: The 'user' table is for PUBLIC data.
-- DO NOT add sensitive columns like 'password' to this table.
-- Password and authentication are handled by Supabase's auth system.

-- Create user table to store public user data
CREATE TABLE public.user (
  id uuid NOT NULL,
  username text NOT NULL,
  bio text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_pkey PRIMARY KEY (id),
  CONSTRAINT user_username_key UNIQUE (username),
  CONSTRAINT user_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);
ALTER TABLE public.user REPLICA IDENTITY FULL;

-- Create chat table to store chat messages
CREATE TABLE public.chat (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sender_id uuid NOT NULL,
  receiver_id uuid NOT NULL,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  is_read boolean NOT NULL DEFAULT false,
  CONSTRAINT chat_pkey PRIMARY KEY (id),
  CONSTRAINT chat_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.user(id) ON DELETE CASCADE,
  CONSTRAINT chat_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.user(id) ON DELETE CASCADE
);
ALTER TABLE public.chat REPLICA IDENTITY FULL;


-- Function to create a user profile for a new auth user
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user (id, username, bio)
  VALUES (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'bio');
  RETURN new;
END;
$$;

-- Trigger to call the function when a new user signs up
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Enable Row Level Security (RLS) for tables
ALTER TABLE public.user ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat ENABLE ROW LEVEL SECURITY;

-- RLS Policies for user profiles
CREATE POLICY "Allow authenticated users to view all user profiles"
ON public.user FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Allow users to update their own profile"
ON public.user FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- RLS Policies for chat messages
CREATE POLICY "Allow users to view their own messages"
ON public.chat FOR SELECT
TO authenticated
USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

CREATE POLICY "Allow users to send messages"
ON public.chat FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = sender_id);

CREATE POLICY "Allow users to update read status of their messages"
ON public.chat FOR UPDATE
TO authenticated
USING (auth.uid() = receiver_id)
WITH CHECK (auth.uid() = receiver_id);`;

  return (
    <div className="h-screen w-screen flex items-center justify-center bg-slate-100 dark:bg-slate-900 p-4">
      <div className="bg-white dark:bg-slate-800 p-8 rounded-lg shadow-lg max-w-3xl w-full">
        <h2 className="text-2xl font-bold text-red-500 mb-4">Database Configuration Required</h2>
        <p className="text-slate-600 dark:text-slate-300 mb-2">
          <strong>Error:</strong> {error}
        </p>
        <p className="text-slate-600 dark:text-slate-300 mb-4">
          It looks like your database isn't set up yet. Please follow these steps:
        </p>
        <ol className="list-decimal list-inside text-slate-600 dark:text-slate-300 mb-4 space-y-2">
          <li>Go to your Supabase project dashboard.</li>
          <li>Navigate to the <strong>SQL Editor</strong> section in the sidebar.</li>
          <li>Click <strong>"+ New query"</strong>.</li>
          <li>Copy the entire SQL script below and paste it into the editor.</li>
          <li>Click the <strong>"RUN"</strong> button.</li>
        </ol>
        <div className="bg-slate-100 dark:bg-slate-900 p-4 rounded-md">
          <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-200 mb-2">SQL Setup Script:</h3>
          <pre className="text-sm text-slate-500 dark:text-slate-400 overflow-auto max-h-60 p-2 bg-slate-200 dark:bg-slate-700 rounded">
            <code>
              {sqlScript}
            </code>
          </pre>
        </div>
        <p className="text-slate-500 dark:text-slate-400 mt-4 text-center">
          After running the script, please refresh this page.
        </p>
      </div>
    </div>
  );
};

const SchemaErrorGuide: React.FC<{ title: string; message: React.ReactNode }> = ({ title, message }) => (
  <div className="h-screen w-screen flex items-center justify-center bg-slate-100 dark:bg-slate-900 p-4">
    <div className="bg-white dark:bg-slate-800 p-8 rounded-lg shadow-lg max-w-3xl w-full">
      <h2 className="text-2xl font-bold text-red-500 mb-4">{title}</h2>
      <div className="text-slate-600 dark:text-slate-300">{message}</div>
    </div>
  </div>
);

const SunIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="5"/><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/></svg>
);
const MoonIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>
);

const PencilIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg>
);

const LogoutIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
);

const ReplyIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-slate-500 dark:text-slate-400"><polyline points="9 17 4 12 9 7"/><path d="M20 18v-2a4 4 0 0 0-4-4H4"/></svg>
);

const CloseIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
);

const NewChatIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><line x1="19" x2="19" y1="8" y2="14"/><line x1="22" x2="16" y1="11" y2="11"/></svg>
);

const SingleCheckIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-slate-400"><path d="M20 6 9 17l-5-5"/></svg>
);
const DoubleCheckIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-sky-400 dark:text-sky-300"><path d="M18 6 7 17l-5-5"/><path d="m22 6-11 11-4-4"/></svg>
);

const formatTime = (timestamp: string) => {
  if (!timestamp) return '';
  const date = new Date(timestamp);
  return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: true });
};


const ChatPage: React.FC<ChatPageProps> = ({ session, theme, toggleTheme }) => {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [allUsers, setAllUsers] = useState<Profile[]>([]);
  const [conversationPartners, setConversationPartners] = useState<Profile[]>([]);
  const [filteredConversations, setFilteredConversations] = useState<Profile[]>([]);
  const [selectedUser, setSelectedUser] = useState<Profile | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [newMessage, setNewMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [onlineUsers, setOnlineUsers] = useState<Record<string, PresenceState>>({});
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const presenceChannelRef = useRef<RealtimeChannel | null>(null);
  const [dbSetupError, setDbSetupError] = useState<string | null>(null);
  const [schemaError, setSchemaError] = useState<{title: string, message: React.ReactNode} | null>(null);
  const [touchStart, setTouchStart] = useState<number | null>(null);

  const [isEditBioModalOpen, setIsEditBioModalOpen] = useState(false);
  const [isNewChatModalOpen, setIsNewChatModalOpen] = useState(false);
  const [newUserSearchQuery, setNewUserSearchQuery] = useState('');
  const [newChatSearchResults, setNewChatSearchResults] = useState<Profile[]>([]);
  const [newBio, setNewBio] = useState('');
  
  const [replyingTo, setReplyingTo] = useState<Message | null>(null);
  const [swipeX, setSwipeX] = useState<Record<number, number>>({});
  const [isSwiping, setIsSwiping] = useState<number | null>(null);
  const touchStartPosRef = useRef<Record<number, { x: number; y: number }>>({});


  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useLayoutEffect(scrollToBottom, [messages]);
  
  const handleLogout = async () => {
    if(presenceChannelRef.current) {
        await presenceChannelRef.current.untrack();
    }
    await supabase.auth.signOut();
  };

  const handleTouchStart = (e: React.TouchEvent) => {
    setTouchStart(e.targetTouches[0].clientX);
  };

  const handleTouchMove = (e: React.TouchEvent) => {
    if (touchStart === null) return;
    const currentX = e.targetTouches[0].clientX;
    const diff = currentX - touchStart;
    // Swipe right to go back
    if (diff > 50) {
      setSelectedUser(null);
      setTouchStart(null);
    }
  };

  const fetchProfileAndUsers = useCallback(async () => {
    // Check for user table
    const { data: profileData, error: profileError } = await supabase
      .from('user')
      .select('*')
      .eq('id', session.user.id)
      .single();

    if (profileError) {
      if (profileError.code === '42P01') { // undefined_table
        setDbSetupError("The 'user' table is missing from your database.");
        return;
      }
      // Self-healing for missing profile row
      if (profileError.code === 'PGRST116') {
        console.warn('Profile not found for current user, creating one.');
        const { user } = session;
        if (!user.user_metadata || !user.user_metadata.username) {
            console.error("User metadata is missing, cannot create profile. Logging out.");
            handleLogout();
            return;
        }

        const newProfileData = {
          id: user.id,
          username: user.user_metadata.username,
          bio: user.user_metadata.bio || null,
        };
        
        const { data: createdProfile, error: insertError } = await supabase.from('user').insert(newProfileData).select().single();

        if (insertError) {
            if (insertError.code === '23505') { // duplicate key
                console.warn("Duplicate key on profile insert, assuming trigger worked. Refetching profile.");
                const { data: refetchedProfile, error: refetchError } = await supabase
                    .from('user')
                    .select('*')
                    .eq('id', session.user.id)
                    .single();
                if (refetchError) {
                    console.error("Failed to refetch profile after duplicate key error:", refetchError.message);
                } else if (refetchedProfile) {
                    setProfile(refetchedProfile);
                    setNewBio(refetchedProfile.bio || '');
                }
                return;
            }

          if (insertError.message.includes('null value in column "password" of relation "user"')) {
            setSchemaError({
              title: "Critical Database Schema Error",
              message: (
                <div>
                  <p className="mb-4">
                    The application has detected a critical error with your database setup. Your <strong>'user'</strong> table incorrectly contains a <strong>'password'</strong> column which must be removed.
                  </p>
                  <p className="mb-4">
                    The <strong>'user'</strong> table is for public profile information (like username and bio). Password management is handled securely and automatically by Supabase's built-in authentication system.
                  </p>
                  <p className="font-bold mb-2">To fix this, you must remove the 'password' column:</p>
                  <div className="bg-slate-100 dark:bg-slate-900 p-4 rounded-md">
                    <p className="font-semibold mb-2">Option 1: Use the Table Editor</p>
                    <ol className="list-decimal list-inside space-y-2 mb-4">
                        <li>Go to your Supabase project's <strong>Table Editor</strong>.</li>
                        <li>Select the <strong>'user'</strong> table.</li>
                        <li>Find the <strong>'password'</strong> column, click the three dots (...), and select <strong>"Delete column"</strong>.</li>
                        <li>Confirm the deletion.</li>
                    </ol>
                    <p className="font-semibold mb-2">Option 2: Run a SQL Command</p>
                     <p className="mb-2">In the <strong>SQL Editor</strong>, run the following command:</p>
                    <pre className="text-sm text-slate-500 dark:text-slate-400 overflow-auto p-2 bg-slate-200 dark:bg-slate-700 rounded">
                        <code>
                            ALTER TABLE public.user DROP COLUMN IF EXISTS password;
                        </code>
                    </pre>
                  </div>
                  <p className="text-center mt-6">After removing the column, please refresh this page.</p>
                </div>
              )
            });
            return;
          }
          console.error('Error creating profile:', insertError.message);
        } else if (createdProfile) {
          setProfile(createdProfile);
          setNewBio(createdProfile.bio || '');
        }
      } else {
        console.error('Error fetching profile:', profileError.message);
      }
    } else if (profileData) {
      setProfile(profileData);
      setNewBio(profileData.bio || '');
    }

    const { data: usersData, error: usersError } = await supabase
        .from('user')
        .select('*')
        .neq('id', session.user.id);
    
    if (usersError) {
        if(usersError.code !== '42P01') {
            console.error('Error fetching users:', usersError.message);
        }
    } else {
        setAllUsers(usersData);
    }

    const { data: messagesData, error: messagesError } = await supabase
        .from('chat')
        .select('sender_id, receiver_id')
        .or(`sender_id.eq.${session.user.id},receiver_id.eq.${session.user.id}`);
        
    if (messagesError) {
        if (messagesError.code !== '42P01') {
            console.error('Error fetching conversation partners:', messagesError.message);
        }
    } else if (messagesData) {
        const partnerIds = new Set<string>();
        messagesData.forEach(msg => {
            if (msg.sender_id !== session.user.id) partnerIds.add(msg.sender_id);
            if (msg.receiver_id !== session.user.id) partnerIds.add(msg.receiver_id);
        });

        if (partnerIds.size > 0) {
            const { data: partners, error: partnersError } = await supabase
                .from('user')
                .select('*')
                .in('id', Array.from(partnerIds));
            
            if (partnersError) {
                console.error('Error fetching partner profiles:', partnersError.message);
            } else if (partners) {
                setConversationPartners(partners);
            }
        }
    }
  }, [session]);

  useEffect(() => {
    fetchProfileAndUsers();
  }, [fetchProfileAndUsers]);
  
  useEffect(() => {
    if (!profile) return;
    
    const channel = supabase.channel('online-users', {
        config: { presence: { key: profile.id.toString() } },
    });

    channel.on('presence', { event: 'sync' }, () => {
        const presenceState = channel.presenceState<PresenceState>();
        const presences: Record<string, PresenceState> = {};
        for (const id in presenceState) {
            const user = (presenceState[id] as unknown as PresenceState[])[0];
            if (user) presences[user.user_id] = user;
        }
        setOnlineUsers(presences);
    });

    channel.on('presence', { event: 'join' }, ({ newPresences }) => {
        setOnlineUsers(prev => {
            const updated = { ...prev };
            (newPresences as unknown as PresenceState[]).forEach(user => { updated[user.user_id] = user; });
            return updated;
        });
    });
    
    channel.on('presence', { event: 'leave' }, ({ leftPresences }) => {
        setOnlineUsers(prev => {
            const updated = { ...prev };
            (leftPresences as unknown as PresenceState[]).forEach(user => { delete updated[user.user_id]; });
            return updated;
        });
    });

    channel.subscribe(async (status) => {
        if (status === 'SUBSCRIBED') {
            await channel.track({ user_id: profile.id, username: profile.username });
        }
    });

    presenceChannelRef.current = channel;

    return () => {
        if (presenceChannelRef.current) {
            supabase.removeChannel(presenceChannelRef.current);
        }
    };
}, [profile]);
  
  useEffect(() => {
    if (searchQuery.trim() === '') {
      setFilteredConversations(conversationPartners);
    } else {
      const lowercasedQuery = searchQuery.toLowerCase();
      const filtered = conversationPartners.filter(user => 
        user.username.toLowerCase().includes(lowercasedQuery)
      );
      setFilteredConversations(filtered);
    }
  }, [searchQuery, conversationPartners]);

  useEffect(() => {
    const trimmedQuery = newUserSearchQuery.trim();
    if (trimmedQuery.length < 4) {
      setNewChatSearchResults([]);
    } else {
      const lowercasedQuery = trimmedQuery.toLowerCase();
      const filtered = allUsers.filter(user => 
          user.username.toLowerCase().includes(lowercasedQuery)
      );
      setNewChatSearchResults(filtered);
    }
  }, [newUserSearchQuery, allUsers]);

  useEffect(() => {
    if (!selectedUser) return;
    
    const fetchAndMarkMessages = async () => {
      setLoading(true);
      const { data, error } = await supabase
        .from('chat')
        .select('*')
        .or(
          `and(sender_id.eq.${session.user.id},receiver_id.eq.${selectedUser.id}),and(sender_id.eq.${selectedUser.id},receiver_id.eq.${session.user.id})`
        )
        .order('created_at', { ascending: true });

      if (error) {
        if (error.code === '42P01') {
            setDbSetupError("The 'chat' table is missing from your database.");
        } else if (error.code === '42703' && error.message.includes('column "created_at" does not exist')) {
             setSchemaError({
                title: "Database Schema Mismatch",
                message: (
                    <div>
                        <p className="mb-4">The application failed to load messages. This is because your <strong>'chat'</strong> table is missing a required column named <strong>'created_at'</strong>.</p>
                        <p className="font-bold mb-2">To fix this, you must add the missing column:</p>
                        <div className="bg-slate-100 dark:bg-slate-900 p-4 rounded-md mb-4">
                             <p className="font-semibold mb-2">Option 1: Use the Supabase Table Editor (Recommended)</p>
                            <ol className="list-decimal list-inside space-y-2">
                                <li>In your Supabase project, go to the <strong>Table Editor</strong>.</li>
                                <li>Select the <strong>'chat'</strong> table.</li>
                                <li>Click the <strong>"+ Add column"</strong> button.</li>
                                <li>Fill in the form with these exact settings:
                                    <ul className="list-disc list-inside ml-6 mt-2 text-slate-500 dark:text-slate-400">
                                        <li><strong>Name:</strong> <code className="bg-slate-200 dark:bg-slate-700 px-1 rounded">created_at</code></li>
                                        <li><strong>Type:</strong> <code className="bg-slate-200 dark:bg-slate-700 px-1 rounded">timestamptz</code></li>
                                        <li>For <strong>Default Value</strong>, select <code className="bg-slate-200 dark:bg-slate-700 px-1 rounded">now()</code>.</li>
                                        <li>Make sure the <strong>Is Nullable</strong> toggle is <span className="font-bold text-sky-500">OFF</span> (unchecked).</li>
                                    </ul>
                                </li>
                                <li>Click <strong>"Save"</strong>.</li>
                            </ol>
                        </div>
                        <div className="bg-slate-100 dark:bg-slate-900 p-4 rounded-md">
                            <p className="font-semibold mb-2">Option 2: Run a SQL Command</p>
                            <p className="mb-2">In the <strong>SQL Editor</strong>, copy and run this exact command:</p>
                            <pre className="text-sm text-slate-500 dark:text-slate-400 overflow-auto p-2 bg-slate-200 dark:bg-slate-700 rounded">
                                <code>{'ALTER TABLE public.chat ADD COLUMN created_at timestamptz NOT NULL DEFAULT now();'}</code>
                            </pre>
                        </div>
                        <p className="text-center mt-6 font-semibold">After adding the column, please refresh this page.</p>
                    </div>
                )
            });
        } else {
            console.error('Error fetching messages:', error.message);
        }
      } else if (data) {
        setMessages(data);
        const unreadMessageIds = data
          .filter(m => m.receiver_id === session.user.id && !m.is_read)
          .map(m => m.id);
        if (unreadMessageIds.length > 0) {
            await supabase
              .from('chat')
              .update({ is_read: true })
              .in('id', unreadMessageIds);
        }
      }
      setLoading(false);
    };
    fetchAndMarkMessages();

    const messageSubscription = supabase
      .channel(`messages:${session.user.id}:${selectedUser.id}`)
      .on('postgres_changes', { 
          event: 'INSERT', 
          schema: 'public', 
          table: 'chat',
          filter: `receiver_id=eq.${session.user.id}` 
        }, 
        (payload) => {
            if((payload.new as Message).sender_id === selectedUser.id) {
                setMessages(m => [...m, payload.new as Message]);
            }
        }
      )
      .on('postgres_changes', {
        event: 'UPDATE',
        schema: 'public',
        table: 'chat',
        filter: `sender_id=eq.${session.user.id}`
      }, (payload) => {
        const updatedMessage = payload.new as Message;
        if (updatedMessage.receiver_id === selectedUser.id) {
          setMessages(currentMessages =>
            currentMessages.map(msg =>
              msg.id === updatedMessage.id ? { ...msg, is_read: updatedMessage.is_read } : msg
            )
          );
        }
      })
      .subscribe();
    
    return () => {
        supabase.removeChannel(messageSubscription);
    };
  }, [selectedUser, session.user.id]);

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (newMessage.trim() === '' || !selectedUser) return;

    let finalContent = newMessage.trim();
    if (replyingTo) {
      // Prepending a quote block
      const quotedText = `>${replyingTo.content.replace(/\n/g, '\n> ')}`;
      finalContent = `${quotedText}\n\n${finalContent}`;
    }

    const messageToInsert = {
      sender_id: session.user.id,
      receiver_id: selectedUser.id,
      content: finalContent,
      is_read: false,
    };
    
    const { data, error } = await supabase.from('chat').insert(messageToInsert).select();
    
    if (error) {
        console.error('Error sending message:', error.message);
        return;
    }
    
    if (data) {
        setMessages(m => [...m, data[0]]);
    }
    setNewMessage('');
    setReplyingTo(null);
  };
  
  const handleUpdateBio = async () => {
    if (!profile) return;
    const { data, error } = await supabase
      .from('user')
      .update({ bio: newBio })
      .eq('id', profile.id)
      .select()
      .single();

    if (data) {
      setProfile(data);
      setIsEditBioModalOpen(false);
    }
    if (error) {
      console.error('Error updating bio:', error.message);
    }
  };

  const handleSwipeStart = (e: React.TouchEvent, msgId: number) => {
    setIsSwiping(msgId);
    touchStartPosRef.current[msgId] = { x: e.targetTouches[0].clientX, y: e.targetTouches[0].clientY };
  };

  const handleSwipeMove = (e: React.TouchEvent, msgId: number) => {
    if (!touchStartPosRef.current[msgId]) return;
    
    const startPos = touchStartPosRef.current[msgId];
    const touchX = e.targetTouches[0].clientX;
    const touchY = e.targetTouches[0].clientY;
    const deltaX = touchX - startPos.x;
    const deltaY = touchY - startPos.y;

    if (Math.abs(deltaX) > Math.abs(deltaY) + 5) { // Prioritize horizontal movement
      if (deltaX < 0) { // Swipe left
        const newX = Math.max(deltaX, -80);
        setSwipeX(prev => ({ ...prev, [msgId]: newX }));
      }
    }
  };

  const handleSwipeEnd = (msg: Message) => {
    const msgId = msg.id;
    setIsSwiping(null);
    const currentSwipeX = swipeX[msgId] || 0;
    if (currentSwipeX < -50) { // Threshold
        setReplyingTo(msg);
        if (navigator.vibrate) navigator.vibrate(50);
    }
    setSwipeX(prev => ({ ...prev, [msgId]: 0 }));
    delete touchStartPosRef.current[msgId];
  };
  
  const handleSelectUserFromModal = (user: Profile) => {
    setSelectedUser(user);
    // Add to conversation list if not already there, for immediate UI feedback
    if (!conversationPartners.some(p => p.id === user.id)) {
        setConversationPartners(prev => [user, ...prev]);
    }
    setIsNewChatModalOpen(false);
    setNewUserSearchQuery('');
  };

  const renderMessageContent = (content: string) => {
    const parts = content.split('\n\n');
    const firstPart = parts[0];
    const isQuote = firstPart.startsWith('>');

    if (isQuote) {
      const quote = firstPart.replace(/^> ?/gm, '');
      const restOfMessage = parts.slice(1).join('\n\n');
      return (
        <>
          <div className="p-2 rounded-md bg-black bg-opacity-10 dark:bg-white dark:bg-opacity-10 border-l-2 border-sky-300 dark:border-sky-200 mb-1 opacity-80">
            <p className="text-sm italic whitespace-pre-wrap">{quote}</p>
          </div>
          <p className="break-words whitespace-pre-wrap">{restOfMessage}</p>
        </>
      );
    }
    return <p className="break-words whitespace-pre-wrap">{content}</p>;
  };
  
  if (schemaError) {
    return <SchemaErrorGuide title={schemaError.title} message={schemaError.message} />;
  }

  if (dbSetupError) {
    return <DatabaseSetupGuide error={dbSetupError} />;
  }

  return (
    <div className="h-screen w-screen flex flex-col bg-slate-100 dark:bg-slate-900 text-slate-800 dark:text-white">
      {!selectedUser && (
        <header className="flex items-center justify-between p-4 bg-white dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700 flex-shrink-0">
          <div className="flex items-center gap-4">
            {profile ? (
              <>
                <Avatar username={profile.username} isOnline={true} size="md" />
                <div className="flex items-center gap-2">
                    <div>
                      <h2 className="font-bold text-lg text-slate-900 dark:text-white">{profile.username}</h2>
                      <p className="text-sm text-slate-500 dark:text-slate-400 truncate max-w-xs">{profile.bio || 'No bio yet.'}</p>
                    </div>
                    <button onClick={() => setIsEditBioModalOpen(true)} className="p-2 rounded-full text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700 hover:text-slate-800 dark:hover:text-slate-200 transition-colors flex-shrink-0" aria-label="Edit bio">
                        <PencilIcon />
                    </button>
                </div>
              </>
            ) : (
               <div className="h-10 w-48 bg-slate-200 dark:bg-slate-700 animate-pulse rounded"></div>
            )}
          </div>
          <div className="text-xl font-bold text-slate-900 dark:text-white hidden sm:block">Chat App</div>
          <div className="flex items-center gap-2">
            <button onClick={handleLogout} className="p-2 rounded-full text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors" aria-label="Logout">
                <LogoutIcon />
            </button>
             <button onClick={toggleTheme} className="p-2 rounded-full text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors" aria-label="Toggle theme">
              {theme === 'light' ? <MoonIcon /> : <SunIcon />}
            </button>
          </div>
        </header>
      )}
      <div className="flex flex-grow overflow-hidden">
        <div className={`relative w-full md:w-1/3 lg:w-1/4 bg-slate-50 dark:bg-slate-800 p-4 flex flex-col transition-all duration-300 ${selectedUser ? 'hidden md:flex' : 'flex'}`}>
          <div className="relative mb-4">
            <input
              type="text"
              placeholder="Search in chats..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-slate-200 dark:bg-slate-700 text-slate-900 dark:text-white px-4 py-2 rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500"
            />
          </div>
          <div className="flex-grow overflow-y-auto">
            {filteredConversations.length > 0 ? (
              filteredConversations.map((user) => (
                <div
                  key={user.id}
                  onClick={() => setSelectedUser(user)}
                  className="flex items-center gap-3 p-3 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 cursor-pointer"
                >
                  <Avatar username={user.username} isOnline={!!onlineUsers[user.id]} />
                  <span className="font-semibold">{user.username}</span>
                </div>
              ))
            ) : (
              <p className="text-slate-400 dark:text-slate-500 text-center p-4">
                {searchQuery
                  ? `No chats matching '${searchQuery}'`
                  : 'No conversations. Start a new chat to begin.'
                }
              </p>
            )}
          </div>
          <button
            onClick={() => setIsNewChatModalOpen(true)}
            className="absolute bottom-6 right-6 bg-sky-600 hover:bg-sky-700 text-white p-4 rounded-full shadow-lg transition-transform hover:scale-110 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500 dark:focus:ring-offset-slate-800"
            aria-label="Start new chat"
          >
            <NewChatIcon />
          </button>
        </div>

        <div 
          className={`w-full md:w-2/3 lg:w-3/4 flex flex-col bg-white dark:bg-slate-900 transition-all duration-300 ${selectedUser ? 'flex' : 'hidden md:flex'}`}
          onTouchStart={handleTouchStart}
          onTouchMove={handleTouchMove}
          onTouchEnd={() => setTouchStart(null)}
        >
          {selectedUser ? (
            <>
              <div className="flex items-center gap-4 p-4 bg-white dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700">
                  <button onClick={() => setSelectedUser(null)} className="md:hidden text-slate-500 dark:text-slate-300">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" /></svg>
                  </button>
                <Avatar username={selectedUser.username} isOnline={!!onlineUsers[selectedUser.id]} />
                <div>
                  <h3 className="text-lg font-bold">{selectedUser.username}</h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400">{onlineUsers[selectedUser.id] ? 'Online' : 'Offline'}</p>
                </div>
              </div>
              <div className="flex-grow p-4 overflow-y-auto">
                {loading ? (
                  <div className="flex justify-center items-center h-full"><p>Loading messages...</p></div>
                ) : (
                  messages.map((msg) => (
                    <div key={msg.id} className={`flex mb-2 ${msg.sender_id === session.user.id ? 'justify-end' : 'justify-start'}`}>
                      <div className="relative">
                        <div className={`absolute inset-y-0 right-0 flex items-center pr-4 -z-10`}>
                           <span style={{ opacity: Math.min(1, Math.abs(swipeX[msg.id] || 0) / 60) }}>
                             <ReplyIcon />
                           </span>
                        </div>
                        <div 
                            className={`max-w-xs lg:max-w-md px-3 pt-2 pb-1 rounded-lg ${msg.sender_id === session.user.id ? 'bg-blue-600 text-white' : 'bg-slate-200 dark:bg-slate-700 text-slate-800 dark:text-slate-200'}`}
                            style={{ transform: `translateX(${swipeX[msg.id] || 0}px)`, transition: isSwiping === msg.id ? 'none' : 'transform 0.3s ease-out' }}
                            onTouchStart={(e) => handleSwipeStart(e, msg.id)}
                            onTouchMove={(e) => handleSwipeMove(e, msg.id)}
                            onTouchEnd={() => handleSwipeEnd(msg)}
                        >
                          <div>{renderMessageContent(msg.content)}</div>
                          <div className="flex items-center justify-end gap-1.5 mt-1 opacity-90">
                            <span className="text-xs">{formatTime(msg.created_at)}</span>
                            {msg.sender_id === session.user.id && (
                              msg.is_read ? <DoubleCheckIcon /> : <SingleCheckIcon />
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))
                )}
                <div ref={messagesEndRef} />
              </div>

              {replyingTo && (
                <div className="p-2 bg-slate-200 dark:bg-slate-700 border-t border-slate-300 dark:border-slate-600">
                    <div className="flex justify-between items-center">
                        <div>
                            <p className="font-bold text-sky-600 dark:text-sky-400 text-sm">
                                Replying to {replyingTo.sender_id === profile?.id ? 'Yourself' : selectedUser?.username}
                            </p>
                            <p className="text-sm text-slate-500 dark:text-slate-400 truncate max-w-xs sm:max-w-sm md:max-w-md">
                                {replyingTo.content.split('\n\n').pop()}
                            </p>
                        </div>
                        <button onClick={() => setReplyingTo(null)} className="p-1 rounded-full hover:bg-slate-300 dark:hover:bg-slate-600">
                            <CloseIcon />
                        </button>
                    </div>
                </div>
              )}

              <form onSubmit={handleSendMessage} className="p-4 bg-white dark:bg-slate-800 border-t border-slate-200 dark:border-slate-700 flex items-center gap-4">
                <input
                  type="text"
                  value={newMessage}
                  onChange={(e) => setNewMessage(e.target.value)}
                  placeholder="Type a message..."
                  className="flex-grow bg-slate-100 dark:bg-slate-700 text-slate-900 dark:text-white px-4 py-2 rounded-full focus:outline-none focus:ring-2 focus:ring-sky-500"
                />
                <button type="submit" className="bg-sky-600 hover:bg-sky-700 text-white font-bold p-2 rounded-full">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 12h14M12 5l7 7-7 7" />
                  </svg>
                </button>
              </form>
            </>
          ) : (
            <div className="flex items-center justify-center h-full text-slate-400 dark:text-slate-500">
              <p>Select a conversation or search to start a new one</p>
            </div>
          )}
        </div>
      </div>
      
      {isEditBioModalOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-slate-800 p-6 rounded-lg w-full max-w-md">
            <h3 className="text-xl font-bold mb-4">Edit Your Bio</h3>
            <textarea
              value={newBio}
              onChange={(e) => setNewBio(e.target.value)}
              className="w-full h-32 bg-slate-100 dark:bg-slate-700 text-slate-900 dark:text-white p-2 rounded-md mb-4"
              placeholder="Tell us about yourself..."
            />
            <div className="flex justify-end gap-4">
              <button onClick={() => setIsEditBioModalOpen(false)} className="bg-slate-200 hover:bg-slate-300 dark:bg-slate-600 dark:hover:bg-slate-500 text-slate-800 dark:text-white px-4 py-2 rounded-md">Cancel</button>
              <button onClick={handleUpdateBio} className="bg-sky-600 hover:bg-sky-700 text-white px-4 py-2 rounded-md">Save</button>
            </div>
          </div>
        </div>
      )}
      
      {isNewChatModalOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-slate-800 p-6 rounded-lg w-full max-w-md flex flex-col max-h-[80vh]">
            <div className="flex justify-between items-center mb-4 flex-shrink-0">
                <h3 className="text-xl font-bold">Start a New Chat</h3>
                <button onClick={() => setIsNewChatModalOpen(false)} className="p-1 rounded-full hover:bg-slate-200 dark:hover:bg-slate-700">
                    <CloseIcon />
                </button>
            </div>
            <input
              type="text"
              placeholder="Search for a user..."
              value={newUserSearchQuery}
              onChange={(e) => setNewUserSearchQuery(e.target.value)}
              className="w-full bg-slate-100 dark:bg-slate-700 text-slate-900 dark:text-white px-4 py-2 rounded-lg mb-4 flex-shrink-0 focus:outline-none focus:ring-2 focus:ring-sky-500"
              autoFocus
            />
            <div className="flex-grow overflow-y-auto">
                {newChatSearchResults.length > 0 ? (
                    newChatSearchResults.map((user) => (
                        <div
                            key={user.id}
                            onClick={() => handleSelectUserFromModal(user)}
                            className="flex items-center gap-3 p-3 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 cursor-pointer"
                        >
                            <Avatar username={user.username} isOnline={!!onlineUsers[user.id]} />
                            <span className="font-semibold">{user.username}</span>
                        </div>
                    ))
                ) : (
                    <p className="text-slate-400 dark:text-slate-500 text-center p-4">
                        {newUserSearchQuery.trim().length < 4
                            ? 'Type at least 4 characters to search.'
                            : 'No users found.'
                        }
                    </p>
                )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ChatPage;